#
# Makefile for the Ingenic JZ4740.
#

# Object file lists.

obj-y += prom.o irq.o time.o reset.o setup.o dma.o \
	gpio.o clock.o platform.o

obj-$(CONFIG_DEBUG_FS) += clock-debugfs.o

# board specific support

obj-$(CONFIG_JZ4740_N516)	+= board-n516.o
obj-$(CONFIG_JZ4740_N516_DISPLAY)	+= board-n516-display.o

# PM support

obj-$(CONFIG_PM)         += pm.o

